# TODO 填写数据库连接信息
spring:
  jackson:
    deserialization:
      fail-on-unknown-properties: false
  profiles:
    active: dev
  main:
    allow-circular-references: true
  application:
    name: kuangkuang
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kuangkuang?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: zty
    password: 102800
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/kuangkuang?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: zty
      password: 102800
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: deepseek-r1:8b
#        TODO 设置apikey
    openai:
      api-key: 123456
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest



server:
  port: 8080
  address: 0.0.0.0


logging:
  level:
    com:
      kuangkuang:
        mapper: debug
        service: info
        controller: info
    org.springframework.ai.chat.client.advisor: debug


mybatis:
  #mapper????
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.kuangkuang.kuangkuang.pojo.entity
  configuration:
    #??????
    map-underscore-to-camel-case: true


